services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pv-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: pv-frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf:ro   # <-- add this
    depends_on:
      - backend
    restart: unless-stopped