version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: pv-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - .:/app                # hot-reload: edit code locally, container reloads
      - ./vault-data:/app     # persist vault.db (SQLite) on host
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: pv-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped